add demo of rgb-node:0.1
LNP-BP/rgb-node pull request #104
Opened 2020-11-19 14:09 UTC by St333p

Here is my proposal for a written guide that aims at reproducing the video demo on youtube. The structure is similar to the one I did for lnp-node.

2020-11-19 18:58 UTC, dr-orlovsky approved these changes

2020-11-19 19:00 UTC, dr-orlovsky commented
@UkolovaOlga can you also pls review?

2020-11-19 19:00 UTC, dr-orlovsky commented
And does anybody has the idea why the CI fails?

2020-11-20 14:12 UTC, zoedberg commented
> And does anybody has the idea why the CI fails?

it's missing `apt-get update`, #105 fixes that

2020-12-03 23:19 UTC, UkolovaOlga requested changes
Minor linguistic changes required

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +In this demo, `rgb-node-0` takes the part of the issuer and transfers some of the newly minted asset to a user, `rgb-node-1`.
>`rgb-node-0` takes the part of the issuer 

better to say 'acts as an issuer'

>minted asset to a user, `rgb-node-1`.

'the' user, not 'a'

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +### premise
Premise with capital 'P'

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +RGB-node does not handle wallet-related functionalities, it just performs RGB-specific tasks over data that will be provided by an external wallet such as [bitcoind](https://github.com/bitcoin/bitcoi
>RGB-node does not handle wallet-related functionalities

'functionality' - singular form

>in order to demonstrate a basic workflow with issuance and a transfer,

...and transfer, no 'a'

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +- an `issuance_utxo` to which `rgb-node-0` will bind newly issued asset
the newly issued asset

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +- a `change_utxo` on which `rgb-node-0` receives asset change
the asset

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +- a `receive_utxo` on which `rgb-node-1` receives asset
the asset

2020-12-03 23:19 UTC, UkolovaOlga commented on doc/demo-0.1/README.md
> +To transfer some amounts of asset to `rgb-node-1` to pay the new invoice, `rgb-node-0` needs to create a consignment and commit to it into a bitcoin transaction. So we will need the invoice and a par
>some amounts of **the** asset to

>utxo from which to take **the** asset

2020-12-05 14:33 UTC, UkolovaOlga approved these changes
Ready for merging

2020-12-05 14:34 UTC, merged